export const types = {
  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",

  FETCH_POSTS: "FETCH_POSTS",
  ADD_POST: "ADD_POST",
  DELETE_POST: "DELETE_POST",
  UPDATE_POST: "UPDATE_POST",

  FETCH_COMMENTS: "FETCH_COMMENTS",

  FETCH_USERS: "FETCH_USERS",
  AUTH_USER: "AUTH_USER",
  LOGOUT_USER: "LOGOUT_USER"
};
